version: "3.8"

volumes:
  db_data:

services:
  database:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: phoenix
    volumes:
      - db_data:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    command: sh -c "sh docker-start.sh"
    environment:
      - USER=wesleyricardi
      - POSTGRES_URL=postgres://postgres:123456789@database:5432
      - DATABASE_URL=postgres://postgres:123456789@database:5432/phoenix
    volumes:
      - .:/app
    depends_on:
      - database